server:
  port: 8004

spring:
  application:
    name: chain-tx
  cloud:
    nacos:
      discovery:
        server-addr: tencent.ecs:28848
  sentinel:
    transport:
      dashboard: tencent.ecs:28070
      port: 9999
  ds-one:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://192.168.111.10:3306/test_tx
  ds-two:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://192.168.111.11:3306/test_tx

product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.share.shareconter.configure.Nacosweight

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.lwl.chaintx.mapper: TRACE
    com.atomikos: INFO
    org.springframework.transaction: TRACE
    org.springframework.jdbc: TRACE
    org.springframework.amqp: DEBUG
    javax.transaction: TRACE
    com.mysql.jdbc: TRACE
    org.apache.ibatis: TRACE
    com.rabbitmq: DEBUG
