server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates: #
            - Path=/user/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: custom-test
          uri: lb://custom-test
          predicates:
            - Path=/test/**
        - id: chain-tx
          uri: lb://chain-tx
          predicates:
            - Path=/chain-tx/**
        - id: mq-db
          uri: lb://mq-db
          predicates:
            - Path=/mq-db/**
  sentinel:
    transport:
      dashboard: localhost:8070
      port: 9999
