server:
  port: 8011

spring:
  application:
    name: atomikos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  sentinel:
    transport:
      dashboard: localhost:8070
      port: 9999
  datasource:
      druid:
        ds-one:
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456
          url: jdbc:mysql://127.0.0.1:3306/test_tx
        ds-two:
          driver-class-name: com.mysql.jdbc.Driver
          username: root
          password: 123456
          url: jdbc:mysql://127.0.0.1:3306/test_tx


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.lwl.chaintx.mapper: TRACE
    com.atomikos: INFO
    org.springframework.transaction: TRACE
    org.springframework.jdbc: TRACE
    org.springframework.amqp: DEBUG
    javax.transaction: TRACE
    com.mysql.jdbc: TRACE
    org.apache.ibatis: TRACE
    com.rabbitmq: DEBUG

product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.share.shareconter.configure.Nacosweight