server:
  port: 8003

spring:
  application:
    name: custom-test

  cloud:
    nacos:
      discovery:
        server-addr: tencent.ecs:28848
  sentinel:
    transport:
      dashboard: tencent.ecs:28070
      port: 9999
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.share.shareconter.configure.Nacosweight

