server:
  port: 8002

spring:
  application:
    name: user-service

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  sentinel:
    transport:
      dashboard: localhost:8070
      port: 9999
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.share.shareconter.configure.Nacosweight
