server:
  port: 8007
spring:
  application:
    name: ticket-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  sentinel:
    transport:
      dashboard: localhost:8070
      port: 9999
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql://192.168.111.10:3306/message_driver_test
  rabbitmq:
    host: 192.168.111.15
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 15000
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 5
        max-concurrency: 10

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.share.shareconter.configure.Nacosweight

logging:
  level:
    com.lwl.chaintx.mapper: DEBUG
    com.atomikos: INFO
    org.springframework.transaction: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.amqp: DEBUG
    javax.transaction: DEBUG
    com.mysql.jdbc: DEBUG
    org.apache.ibatis: DEBUG
    com.rabbitmq: DEBUG